[shell]
program = "/usr/bin/zsh"

[font]
size = 13.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window]
padding = {x=10, y=10}
dynamic_padding = true
decorations = "None"
opacity = 0.95
blur = true


# Set the cursor shape for non-vi (insert) mode
[cursor]
style = {shape="Block", blinking="On"}
unfocused_hollow = true


