theme = "gruvbox_dark_soft"

[keys.normal]
'0' = "goto_line_start"
'$' = "goto_line_end"
C-h = "jump_backward"
C-l = "jump_forward"
C-q = ":config-reload"

A-q = ':lsp-restart'
A-h = ":buffer-previous"
A-l = ":buffer-next"
A-c = ":buffer-close"
A-o = ":config-open"

# See where the 'comment lines' command is, try to change it to gcc
# g-c-c = ""

[editor]
cursorline = true
line-number = "relative"
scrolloff = 5
middle-click-paste = true
shell = ["sh", "-c"]
bufferline = "always"
color-modes = true
gutters = ["spacer", "diagnostics", "spacer", "diff", "spacer", "line-numbers", "spacer"]
workspace-lsp-roots = ["/home/zach/Projects/google-apps-script", "home/zach/Projects/rust-projects"]
[editor.statusline]
separator= " | "
left=["mode", "spinner", "file-base-name"]
center=["register" ,"selections", "diagnostics", "version-control"]
right=["separator", "file-encoding" ,"position", "position-percentage", "separator", "total-line-numbers", "file-line-ending", "file-type", "file-modification-indicator"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden =  false

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
max-wrap = 50 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it  
